---
{{- include "common.serviceAccount" . }}
---
{{- $namespaces := dict
  "integrationsecretnamespace" .Values.argoCD.tssc.namespace
}}
{{- include "common.secretRWRoleBinding" (merge $namespaces .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.postDeployDeleteLabels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
{{- include "common.RoleBinding" . }}
