---
{{- include "common.serviceAccount" . }}
---
{{- $namespaces := dict
  "integrationsecretnamespace" .Values.quay.tssc.namespace
}}
{{- include "common.secretRWRoleBinding" (merge $namespaces .) }}
---
{{- include "common.clusterRoleBinding" . }}
