---
apiVersion: v2
name: tssc-tpa
description: TSSC Trusted Profile Analyzer
type: application
version: "1.6.0"
appVersion: "2.1.0"
dependencies:
  - name: redhat-trusted-profile-analyzer
    version: 1.1.0
    condition: trustedProfileAnalyzer.enabled
